# Generated by Django 5.2.7 on 2025-11-08 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('tasks', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.TextField()),
                ('subcategory', models.CharField(blank=True, max_length=200, null=True)),
                ('worker_assigned', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(max_length=50)),
                ('payment_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('scheduled_at', models.DateTimeField()),
                ('submit_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_categories', to='categories.category')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='tasks.task')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_assignments', to='workers.worker')),
            ],
            options={
                'verbose_name_plural': 'Calling Summaries',
                'db_table': 'calling_summary',
                'ordering': ['-created_at'],
            },
        ),
    ]
