# Generated by Django 5.2.7 on 2025-12-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calling_summary', '0002_alter_callingsummary_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='callingsummary',
            name='action',
            field=models.CharField(default='created', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callingsummary',
            name='changes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
