# Generated by Django 5.2.7 on 2025-12-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calling_summary', '0003_callingsummary_action_callingsummary_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callingsummary',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='callingsummary',
            name='rating',
        ),
        migrations.AlterField(
            model_name='callingsummary',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('worker_assigned', 'Worker Assigned')], default='created', max_length=30),
        ),
    ]
