# Generated by Django 5.2.7 on 2025-12-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calling_summary', '0004_remove_callingsummary_feedback_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callingsummary',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='callingsummary',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('worker_assigned', 'Worker Assigned')], max_length=30),
        ),
        migrations.AlterField(
            model_name='callingsummary',
            name='id',
            field=models.CharField(editable=False, max_length=25, primary_key=True, serialize=False),
        ),
    ]
