# Generated by Django 5.2.7 on 2025-11-08 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=200)),
                ('cust_phone', models.CharField(max_length=15)),
                ('cust_whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('cust_location', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('task_image', models.ImageField(blank=True, null=True, upload_to='tasks/')),
                ('worker_name', models.CharField(blank=True, max_length=200, null=True)),
                ('schedule_date', models.DateTimeField()),
                ('day_service_done', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_received_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='categories.category')),
                ('subcategories', models.ManyToManyField(blank=True, related_name='task_subcategories', to='categories.category')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='workers.worker')),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
