# Generated by Django 5.2.7 on 2025-11-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_id_alter_task_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='location_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
