# Generated by Django 5.2.7 on 2025-11-21 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_location_id'),
        ('tasks', '0003_task_location_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='location_id',
        ),
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='locations.location'),
        ),
    ]
