# Generated by Django 5.2.7 on 2025-11-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_location_id_task_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='worker_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='worker_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
