# Generated by Django 5.2.7 on 2025-12-05 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_alter_requirement_options_alter_requirement_id_and_more'),
        ('tasks', '0005_task_worker_category_task_worker_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='requirements.requirement'),
        ),
    ]
