# Generated by Django 5.2.7 on 2025-11-08 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('whatsapp_no', models.CharField(blank=True, max_length=15, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('aadhar_no', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('geo_location_link', models.URLField(blank=True, null=True)),
                ('last_working_at', models.DateTimeField(blank=True, null=True)),
                ('task_id_lst', models.TextField(blank=True, null=True)),
                ('busy_dates', models.TextField(blank=True, null=True)),
                ('ranking_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('rejected', 'Rejected'), ('under_review', 'Under Review'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('aadhar_img_front', models.ImageField(blank=True, null=True, upload_to='workers/aadhar/')),
                ('aadhar_img_back', models.ImageField(blank=True, null=True, upload_to='workers/aadhar/')),
                ('selfie_img', models.ImageField(blank=True, null=True, upload_to='workers/selfies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location')),
                ('primary_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_workers', to='categories.category')),
                ('secondary_categories', models.ManyToManyField(blank=True, related_name='secondary_workers', to='categories.category')),
            ],
            options={
                'db_table': 'workers',
                'ordering': ['-ranking_score', 'name'],
            },
        ),
    ]
