# Generated by Django 5.2.7 on 2025-11-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.CharField(editable=False, max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
