# Generated by Django 5.2.7 on 2025-11-08 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=15)),
                ('location', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('waiting', 'Waiting'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='categories.category')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='workers.worker')),
            ],
            options={
                'db_table': 'requirements',
                'ordering': ['-created_at'],
            },
        ),
    ]
