# Generated by Django 5.2.7 on 2025-11-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirement',
            options={},
        ),
        migrations.AlterField(
            model_name='requirement',
            name='id',
            field=models.CharField(editable=False, max_length=25, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='requirement',
            table=None,
        ),
    ]
