# Generated by Django 5.2.7 on 2025-11-08 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IVR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('response', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('no_answer', 'No Answer'), ('busy', 'Busy')], max_length=20)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('total_response_time', models.DurationField(blank=True, null=True)),
                ('auto_campaign_name', models.CharField(blank=True, max_length=200, null=True)),
                ('campaign_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('called_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ivr_calls', to='workers.worker')),
            ],
            options={
                'verbose_name': 'IVR Log',
                'verbose_name_plural': 'IVR Logs',
                'db_table': 'ivr',
                'ordering': ['-created_at'],
            },
        ),
    ]
